version: 0.2
phases:
  pre_build:
    commands:
      - echo List directory files...
      - ls
      - echo Installing NPM dependencies
      - npm install
  build:
    commands:
      - echo List active directory...
      - ls
      - echo Build started on `date`
      - npx lessc src/styles/app.less --js --source-map src/styles/app.css
      - echo REACT_APP_ENDPOINT=https://${ApiUrl} >> .env.production
      - echo REACT_APP_AWS_COGNITO_URL=${CognitoDomainUrl} >> .env.production
      - echo REACT_APP_AWS_COGNITO_USER_POOL_ID=${CognitoUserPoolID} >> .env.production
      - echo REACT_APP_AWS_COGNITO_CLIENT_ID=${CognitoAppClientID} >> .env.production
      - npm run build
  post_build:
    commands:
      - ls
      - aws s3 cp --recursive --acl public-read --cache-control="max-age=0, no-cache, no-store, must-revalidate" ./build s3://${DeployBucket}/
      - aws cloudfront create-invalidation --distribution-id ${DistributionId} --paths "/*"
artifacts:
  files:
    - '**/*'
  base-directory: 'build'
