name: Release

on:
  push:
    branches:
      - release
      - staging

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup keys
        env:
          FontAwesomeKey: ${{ secrets.FONT_AWESOME_KEY }}
        run: sed "s/__FontAwesomeKey__/${FontAwesomeKey}/g" .npmrc.template >.npmrc

      - name: Semantic Release
        uses: eco-trip/semantic-release-action@v1.0
        with:
          token: ${{ secrets.MEBBOT }}
          checkout: false
