name: UpdateParent

on:
  push:
    branches:
      - dev
      - staging
      - release

jobs:
  update-parent:
    runs-on: ubuntu-latest
    steps:
      - name: Update parent
        uses: eco-trip/update-submodules-action@v1.0
        with:
          parent: eco-trip/Ecotrip
          submodules: Administration, CP, App
          token: ${{ secrets.MEBBOT }}
          commit_message: 'chore: Update CP [skip ci]'
